In [1]:
import numpy
import seaborn

In [2]:
a = numpy.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a.clip(1,2)

array([1, 1, 2, 2, 2])

In [4]:
a = numpy.arange(5)
a

array([0, 1, 2, 3, 4])

In [5]:
a.compress(a>2)

array([3, 4])

In [9]:
# 计算乘阶
b = numpy.arange(1,5)
b.prod()

24

In [10]:
# 计算数组元素的累积乘积
b = numpy.arange(1,8)
b.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

In [12]:
# 创建一个单位矩阵
eyeData = numpy.eye(4)

In [13]:
# 将数据保存到文件中
numpy.savetxt("eye.txt",eyeData)

In [ ]:
# 加权平均价格
numpy.average(data,weights=v)

In [16]:
# 计算极值（最大值-最小值）
numpy.ptp(b)

6

In [17]:
# 中位数
numpy.median(b)

4.0

In [20]:
numpy.diff(b)

array([1, 1, 1, 1, 1, 1])

In [19]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [1]:
import pandas

In [11]:
data = pandas.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                        'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'key1': ['B0', 'B1', 'B2', 'B3']})

In [12]:
data

key1 key2   A
0   B0   K0  A0
1   B1   K1  A1
2   B2   K0  A2
3   B3   K1  A3

In [14]:
# 是否唯一
data.index.is_unique

True

In [20]:
data.describe()

key1 key2   A
count     4    4   4
unique    4    2   4
top      B2   K0  A1
freq      1    2   1

In [22]:
data.index.get_indexer

<bound method Index.get_indexer of RangeIndex(start=0, stop=4, step=1)>